version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo PRE_BUILD installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo BUILD started on `date`
      - echo BUILD Running tests...
      - npm test
  post_build:
      commands:
      - echo POST_BUILD Tests Complete...
      - echo BUILD completed on `date`  
