version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo INSTALL source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo PRE_BUILD tasks...
  build:
    commands:
      - echo BUILD started on `date`
      - echo BUILD Zipping deployment package...
      - zip -r -q ./lambda-new-authorizer.zip .
  post_build:
      commands:
      - echo POST_BUILD Updating lambda Function...
      - echo BUILD completed on `date`  
artifacts:
  files:
    - package.json
    - package-lock.json
    - lambda-new-authorizer.zip