version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo PRE_BUILD installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo BUILD started on `date`
      - echo BUILD Zipping deployment package...
      #- zip -r -q ./lambda-new-authorizer.zip .
  post_build:
      commands:
      - echo POST_BUILD Updating lambda Function...
      - echo BUILD completed on `date`  
artifacts:
  files:
    - lambda-new-authorizer.zip