version: 0.2

env:
  variables:
    FUNCTION_NAME: lambda-new-authorizer
    BUCKET_NAME: account-a-884069944685-codedeploy-artfacts

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo PRE_BUILD no tasks... 

  build:
    commands:
      - echo POST_BUILD Updating lambda Function...
      - aws lambda update-function-code --function-name ${FUNCTION_NAME} --s3-bucket ${BUCKET_NAME} --s3-key ${FUNCTION_NAME}/${FUNCTION_NAME}.zip
  
  post_build:
      commands:
      - echo POST_BUILD no tasks... 